spring:
  datasource:
    url: jdbc:mysql://localhost:3306/orivehrm
    username: root
    password: Orive@123
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: PAYROLL-SERVICE


  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka
server:
  port: 8085      